//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbnumnaEntities : DbContext
    {
        public dbnumnaEntities()
            : base("name=dbnumnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<dart_corpcode> dart_corpcode { get; set; }
        public virtual DbSet<HashTags> HashTags { get; set; }
        public virtual DbSet<IPOSchedule> IPOSchedule { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<RawData> RawData { get; set; }
        public virtual DbSet<TodoItem> TodoItem { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WiseSaying> WiseSaying { get; set; }
        public virtual DbSet<dart_corpcode2> dart_corpcode2 { get; set; }
        public virtual DbSet<tour_crawlingData> tour_crawlingData { get; set; }
        public virtual DbSet<tour_keyword> tour_keyword { get; set; }
    }
}
